# Generated by Django 2.0.4 on 2018-04-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1)),
                ('ultima_interrupcion', models.DateTimeField(null=True)),
                ('reinicio_ciclo', models.DateTimeField(null=True)),
                ('recibio_interrupcion', models.CharField(max_length=2, null=True)),
                ('inicio_interrupcion', models.CharField(max_length=2, null=True)),
                ('semaforo_replica', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Compania')),
            ],
        ),
    ]
