# Generated by Django 2.0.4 on 2018-04-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaforo',
            name='descripcion',
            field=models.CharField(default='Semaforo', max_length=100),
            preserve_default=False,
        ),
    ]
