# Generated by Django 2.0.4 on 2018-04-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_semaforo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaforo',
            name='inicio_interrupcion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semaforo',
            name='recibio_interrupcion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semaforo',
            name='reinicio_ciclo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semaforo',
            name='semaforo_replica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='semaforo',
            name='ultima_interrupcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
